### ISSUE TITLE
Migrate to rand-core when it is available

### ISSUE THREAD

**Issue by nagisa** [nagisa/rust_rdrand#1]
Don’t need to depend on all the other RNGs, only the interfaces are necessary.

**Comment by nagisa** [comment]
Tracking issue for this seems to be https://github.com/rust-lang-nursery/rand/issues/232

**Comment by dhardy** [comment]
We have a pre-release available: https://crates.io/crates/rand_core/0.1.0-pre.0

**Comment by nagisa** [comment]
I was looking into implementing it, but I got stuck on `[T]::align_to` not yet being implemented, so that will have to happen first.

**Comment by nagisa** [comment]
I released 0.2.0 that depends on rand_core 0.2.0 now.

Yay!

Honestly, implementation of `try_fill_bytes` was a pain and took me *ages*, but hey, I did it :)
