### ISSUE TITLE
Target feature: rdrand / rdrnd

### ISSUE THREAD

**Issue by dhardy** [nagisa/rust_rdrand#10]
Isn't this a typo?

https://github.com/nagisa/rust_rdrand/blob/800e213cc91a83d3bf772398962e7c1f0fcc7825/src/lib.rs#L146

```
$ rustc --print target-features
Available features for this target:
    ...
    rdrnd                         - Support RDRAND instruction.
    rdseed                        - Support RDSEED instruction.
```
This was also referenced in #5 #6 #9.

**Comment by nagisa** [comment]
`--print target-features` probably ends up printing the LLVM names for the features, however rustc has a mapping [as seen here](https://github.com/rust-lang/rust/blob/8af675a07576940ba24e3d91abd10b029b937946/src/librustc_codegen_llvm/llvm_util.rs#L219) which is used to resolve the `target_feature` cfgs.

**Comment by nagisa** [comment]
This prints `true` when compiled with `-Ctarget-features="+rdrnd"`:

```
fn main() {
    println!("{:?}", cfg!(target_feature="rdrand"));
}
```

One could argue that the name mismatch between `-Ctarget-features` and the `target_features` cfg is not great, but that would be an issue report against rustc either way.
