### ISSUE TITLE
Check for buggy AMD hardware

### ISSUE THREAD

**Issue by nagisa** [nagisa/rust_rdrand#12]
Some AMD hardware is buggy and returns success while the data is not exactly random.

See https://github.com/systemd/systemd/pull/12536/commits/1c53d4a070edbec8ad2d384ba0014d0eb6bae077

**Comment by dhardy** [comment]
You may wish to refer to https://github.com/rust-random/getrandom/pull/48.

**Comment by nagisa** [comment]
This is fixed in 0.8.0 now.
