### ISSUE TITLE
Aliasing `word` and `*buffer` is undefined behavior

### ISSUE THREAD

**Issue by MaulingMonkey** [nagisa/rust_rdrand#13]
https://github.com/nagisa/rust_rdrand/blob/26a0a2f9d885fbbb8e14fa47c8a48e366cf15455/src/lib.rs#L359-L362

After this runs, `word` (`&mut u32` or similar) and `*buffer` (`&[u8]`) alias the same memory.  As [a mutable reference cannot be aliased](https://doc.rust-lang.org/nomicon/references.html), this is undefined behavior, unless I'm missing something.

**Comment by nagisa** [comment]
You’re right. Will fix this ASAP.

**Comment by nagisa** [comment]
Fix is in https://github.com/nagisa/rust_rdrand/commit/7af432c6e315fde053d0056d1b7df893a865711a. Waiting for it to go through CI before a new version is released.

**Comment by MaulingMonkey** [comment]
Looks good to me!  👍

**Comment by nagisa** [comment]
Released versions 0.6.0 and 0.5.2 that address this issue.

Thanks for the report!
