### ISSUE TITLE
Bug in `rdrand::RdRand::try_fill_bytes` - destination only partially filled

### ISSUE THREAD

**Issue by kristijantbtl** [nagisa/rust_rdrand#18]
The method `RdRand::try_fill_bytes` works incorrectly in the case where:

- the left end of `dest` is properly aligned, and
- the length of `dest` is larger than and not a multiple of the word size (say, 20 bytes on an 8-byte-word machine).

What happens is the following:

1. The [condition on line 329](https://github.com/nagisa/rust_rdrand/blob/f2fdd528a6103c946a2e9d0961c0592498b36493/src/lib.rs#L329) is `true`;
2. `left` may be an empty slice, while `right` is non-empty [on line 330](https://github.com/nagisa/rust_rdrand/blob/f2fdd528a6103c946a2e9d0961c0592498b36493/src/lib.rs#L330);
3. the [`while` loop condition on line 309](https://github.com/nagisa/rust_rdrand/blob/f2fdd528a6103c946a2e9d0961c0592498b36493/src/lib.rs#L309) is `false`, since `left` was empty;
4. `right` is never touched, and left unfilled.

I have encountered this while writing tests for a use case of generating a 20-byte random vector, where the last 4 bytes were always left unfilled.

The reason the unit test [`fill_fills_all_bytes`](https://github.com/nagisa/rust_rdrand/blob/f2fdd528a6103c946a2e9d0961c0592498b36493/src/lib.rs#L483) doesn't find this is the following:

1. at first, `start == 0` and `end == 128`, meaning they are aligned;
2. then, `start` is modified while `end` remains `128`;
3. `start` stops at the value `17` (unaligned) when `end` first starts being modified;
4. the case where `start` is aligned but `end` is not is never covered.

Simply modifying `end` to start at `127` reproduces the issue for me, where the last `7` bytes of the slice (and `8` of the array) remain zero, and the test fails:

```
test test::fill_fills_all_bytes ... FAILED

failures:

---- test::fill_fills_all_bytes stdout ----
thread 'test::fill_fills_all_bytes' panicked at 'wow, we broke it? 0 127 [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0]', src/lib.rs:514:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::fill_fills_all_bytes
```

**Comment by nagisa** [comment]
Ah, dang! Good catch! I remember writing the `fill_fills_all_bytes` in the first place because I wasn't entirely confident in the implementation back then...

**Comment by nagisa** [comment]
The fix has been published in 0.8.2.

**Comment by kristijantbtl** [comment]
Thank you for the quick response!

Given the nature of this crate and its dependents, wouldn't this warrant [publishing a security advisory](https://rustsec.org/) for version 0.8.1 and below?

**Comment by nagisa** [comment]
Yeah, it wouldn't be a bad idea. Want to report it?
