### ISSUE TITLE
SGX detection confusion

### ISSUE THREAD

**Issue by josephlr** [nagisa/rust_rdrand#9]
Right now this create [unconditionally fails](https://github.com/nagisa/rust_rdrand/blob/800e213cc91a83d3bf772398962e7c1f0fcc7825/src/lib.rs#L149) if the `target_env` is SGX. However, RDRAND was introduced in Ivy Bridge and RDSEED was introduced in Brodwell, while SGX wasn't introduced until Skylake.

@nagisa @akash-fortanix @jethrogb was there a reason why we assume RDRAND/RDSEED is not supported on SGX chips? I understand not trusting CPUID, but there isn't a chip out there that has SGX but doesn't have RDRAND.

**Comment by jethrogb** [comment]
While there is no extant hardware that has SGX but not RDRAND, this might not always be the case. Intel might design a new way for enclaves to get randomness securely in the future. This means you can't just assume RDRAND is available just by virtue of being compiled for SGX.

The `is_x86_feature_detected` implementation here is designed to mimic what the [std macro](https://doc.rust-lang.org/stable/std/macro.is_x86_feature_detected.html) does. The CPUID instruction generates #UD inside SGX, so if you're cross-compiling for SGX and don't have `std`, you can't make any assumptions about how you might detect RDRAND support. The conservative option must be chosen which is to assume it's not supported. To force RDRAND support, you should compile with `-C target-feature=+rdrnd` or set this in your [target specification](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs#L47).

NB. For the `x86_64-fortanix-unknown-sgx` target, improvements to `is_x86_feature_detected` are [being planned](https://github.com/fortanix/rust-sgx/issues/26).

**Comment by jethrogb** [comment]
I think this issue can be closed.
